app/blueprints/users.py
from flask import Blueprint, jsonify, request, current_app, render_template, session, redirect, url_for, copy_current_request_context
from flaskthreads import AppContextThread
from flask_mail import Mail
from flask_mail import Message
import threading
from app.validators.validate import jsonvalues, regularExValidation
from app.models.usersmodel import users
from app.models.dataBase import db
from app.decorators import token_required
import jwt
import datetime


# A blueprint named 'users' to register and login in users

signin = Blueprint('signin', __name__, template_folder="templates")

# sign up endpoint
@signin.route('/signup', methods = ['GET', 'POST'])
def signup():

    """An endpoint to rigister new memmbers"""

    con_cur = db.connectToDatabase(current_app.config['DATABASE_URI'])

    if request.method == 'POST':

        userData = request.form.to_dict()

        dataAvailable = jsonvalues.emptyValues(**userData)

        keysAvailable = jsonvalues.jsonKeys(**userData)

        requiredKeys = ("username", "email", "role", "password", "confirmpassword")

        validKeys = jsonvalues.validKeys(*requiredKeys, **userData) 

        if not dataAvailable:

            return jsonify(
                {
                    'status': 400,
                    'error': 'username, email, role, password or confirmpassword value is missing'
                }
            ), 400
        elif not validKeys:

            return jsonify(
                {
                    'status':400,
                    'error':'Please provide username, email, role, password or confirmpassword'
                }
            ), 400
        elif not keysAvailable:
            return jsonify(
                {
                    'status': 400,
                    'error': 'username, email, role, password or confirmpassword is missing'
                }
            ), 400
        elif userData['password'] != userData['confirmpassword']:
            return jsonify(
                {
                    'status':400,
                    'error':'password and confirmpassword do not match'
                }
            ), 400
        else:

            validEmail = regularExValidation.validEmail(userData['email'])

            dataStrings = (
                userData['username'], userData['email'], userData['role'],
                userData['password'], userData['confirmpassword']
            )

            validStrings = jsonvalues.validString(*dataStrings) 

            if not validEmail:

                return jsonify(
                    {
                        "status": 400, "error": "Please provide a valid email"
                    }
                ), 400

            elif not validStrings:

                    return jsonify(
                        {
                            'status': 400,
                            'error': 'Please provide username, email, role, password or confirmpassword as valid strings values'
                        }
                    ), 400
            else:

                spaceCharacters = jsonvalues.absoluteSpaceCharacters(*dataStrings)

                if spaceCharacters:

                    return jsonify(
                        {
                            "status": 400,
                            "error": "username, email, role, password or confirmpassword values can not be space characters"
                        }
                    ), 400
                newUser = users.addUser(
                    con_cur,userData['username'], userData['email'],
                    userData['role'], userData['password']
                )
                validBoolRole = jsonvalues.validRole(userData["role"])

                if type(newUser) == str:

                    return jsonify({'status': 409, 'error': newUser}), 409

                elif not validBoolRole:

                    return jsonify(
                        {
                            "status": 400,
                            "error": "Please provide a valid boolean role"
                        }
                    ), 400

                else:
                    displayUser = {}
                    displayUser.update(
                        {
                            'userId': newUser['userid'],'fullname': newUser['fullname'],
                            'email': newUser['email'], 'role': newUser['roles']   
                        }
                    )
                    
                    # 'verified': newUser['emailverified']
                    # Sends an email to verify the email address
                    # @copy_current_request_context
                    # def send_email_verification(secret_key, user, current_app):
                    #     ''' Sends a mail to verify email'''

                        # initialise extension
                        # mail = Mail(current_app)

                        # token = users.get_verify_email_token(user['userid'], secret_key)

                        # Email message
                        # email_message = Message(
                        #     'Verify email',
                        #     sender='noreply@demo.com',
                        #     recipients=[user['email']]
                        # )

                        # Email body
                        # email_message.body = 'Visit link to verify email: {} If you did not make this request please ignore this and no changes will be made'.format(url_for('signin.verify_email', token=token, _external=True))
                    
                        # mail.send(email_message)
                    
                    # A thread to send an email
                    # send_email_thread = threading.Thread(target=send_email_verification, args=[current_app.config['SECRET_KEY'], newUser, current_app])

                    # Starts the thread
                    # send_email_thread.start()

                    # if 'x-access-token' in session:
                        # removes x-access-token from the session dictionary
                        # session.pop('x-access-token', None)

                    return jsonify({'status': 201, 'user': displayUser}), 201        
    
    return render_template('signup.html')

# login endpoint
@signin.route('/signin', methods = ['GET', 'POST'])
def login():

    ''' A view function for users to login to their accounts'''

    if request.method == 'POST':

        loginData = request.form.to_dict()

        dataEmpty = jsonvalues.emptyValues(**loginData)

        loginKeys = ('email', 'password')

        validKeys = jsonvalues.validKeys(*loginKeys, **loginData)

        keysExist = jsonvalues.jsonKeys(**loginData)

        if not dataEmpty:

            return jsonify(
                {
                    'status': 400, 'error': 'Please provide values for email and password'
                }
            ), 400

        elif not validKeys:
            return jsonify(
                {
                    'status': 400,
                    'error': 'Please provide email and password as keys'
                }
            ), 400
        elif not keysExist:
            return jsonify(
                {
                    'status': 400, 'error': 'Email and password keys are missing'
                }
            ), 400
        else:

            loginStrings = (loginData['email'], loginData['password'])

            validString = jsonvalues.validString(*loginStrings)

            if not validString:
                return jsonify(
                    {
                        'staus': 400,
                        'error': 'Please provide email and password as valid strings values.'
                    }
                ), 400
            else:
                con_cur = db.connectToDatabase(current_app.config['DATABASE_URI'])

                loginUser = users.userLogin(
                    con_cur, loginData['email'], loginData['password']
                )

                spaceCharacters = jsonvalues.absoluteSpaceCharacters(*loginStrings)

                if spaceCharacters:

                    return jsonify(
                        {
                            "status": 401,
                            "error": "email and password values can not be space characters"
                        }
                    ), 401
                elif type(loginUser) == str:
                    
                    # Please implement the 401 error, it means that the credentials you entered were invalid 
                    return jsonify({'status': 401, 'error': loginUser}), 401

                else:

                    token = jwt.encode(
                        {
                            'userId': loginUser['userid'],
                            'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=120)
                        },
                        'secret', algorithm='HS256'
                    )
                    # decoding the encoded token(which is in bytes). Decoding it will change the bytes to UTF-8 character text. 
                    # serializable by the jsonify function. Otherwise jsonify won't serialize bytes data type.
                    # serialize - is the process of translating data structures or object state into a format that can be stored (for example, in a file or memory buffer)
                    decodedToken = token.decode('UTF-8')

                    session['x-access-token'] = decodedToken

                    return jsonify({'status': 200, 'token': decodedToken}), 200

    return render_template('signin.html')

# User's profile endpoint
@signin.route('/profile')
@token_required
def profile(current_user_id):
    ''' The profile page that has all questions the
    user posted, form to edit personal information
    and a view of that information.
    '''
    return render_template('profile.html')

# Sign out endpoint
@signin.route('/logout')
@token_required
def signout(current_user_id):
    '''
        Logs out the user by removing the

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FindHelp home page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homepage.css') }}">
</head>
<body>

    <!-- Home page body -->
    <div id="home-body">
        <!-- Navigation -->
        <div id="nav">
            <a href="{{ url_for('index') }}" class="navlinks left-link">FindHelp</a>
            <!-- Right navigation links -->
            <div id="right-links">
                    <a href="{{ url_for('signin.login') }}" class="navlinks right-link">Signin</a>
                    <a href="{{ url_for('signin.signup') }}" class="navlinks right-link">Signup</a>
            </div>
        </div>
        <!-- First body section -->
        <div id="first-body-section">
            <h1>Find Solutions</h1>
            <h2>
                Millions of people around the world sharing knowledge and skills. 
            </h2>
            <p>
                A platform that's not limited to a particular field, connect with people whom
                you have same passion and thirst for perfection.
            </p>
        </div>
        <!-- Footer -->
        <div id="footer">
            <li class="footer-item">&#9400; Find-Help 2020</li>     
        </div>
    </div>
    <!-- <script src="js/homepage.js"></script> -->
</body>
</html>

templates/newpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/newpassword.css') }}">
    <title>Create a new password</title>
</head>
<body>
    <!-- body container -->
    <div id="body-container">
        <!-- navigation -->
        <div id="nav">
            <a href="{{ url_for('index') }}" id="left-item">Help</a>
            <div id="right-item">
                <a href="{{ url_for('signin.login') }}" id="signin">Signin</a>
                <a href="{{ url_for('signin.signup') }}" id="signup">Signup</a>
            </div>
        </div>
        <!-- body -->
        <div id="body">
            <!-- new password container-->
            <div id="new-password-container">
                <!-- heading -->
                <h2>Create a new password</h2>
                <!-- Errors container -->
                <div id="newpassword-errors">
                    <!-- Error messages -->
                    <li></li>
                </div>
                <!-- new password form -->
                <form action="#" method="post" id="password-form">
                    <input type="password" name="password" id="password" placeholder="new password">
                    <input type="password" name="confirmpassword" id="confirmpassword" placeholder="confirm new password">
                    <input type="submit" value="Submit" id="submit">
                </form>

            </div>
        </div>
    </div>
<script  src="{{ url_for('static', filename='js/newpassword.js' ) }}"></script>  
</body>
</html>

templates/questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/questions.css') }}">
    <title>questions</title>
</head>
<body>
    <!-- A container for all components -->
    <div id="questions-body">
        <!-- Navigation -->
        <div id="questions-nav">
            <h3><a href="{{ url_for('questions.home_view_questions') }}">Help</a></h3>
            <!-- name and photo -->
            <div id="left-nav">
                <div id="bell">
                    <!-- &#128276; -->
                    <div id="bell-div">
                        <img id="bell-bell" src="{{ url_for('static', filename='img/bell.png') }}" alt="Nofication bell">
                    </div>
                    <div id="badge">3</div>
                    <!-- Notifications -->
                    <div id="notifications">
                        <div class="notification-container" data-answer-noti="1">
                            <div class="question-notification">
                                <a class="anchor-notification" href="#">How do you create classes in python ?
                                    How do you create classes in python ?
                                    How do you create classes in python ?
                                    How do you create classes in python ?
                                </a> 
                            </div>
                            <div class="notification">answers 10 mins ago</div>
                        </div>
                        <div class="notification-container" data-comment="1">
                            <div class="question-notification">
                                <a class="anchor-notification" href="#">How do you create classes in python ?</a> 
                            </div>
                            <div class="notification">comments 30 mins ago</div>
                        </div>
                        <div class="notification-container" data-vote-noti="1">
                            <div class="question-notification">
                                <a class="anchor-notification" href="#">How do you create classes in python ?</a> 
                            </div>
                            <div class="notification">votes 1 hour ago</div>
                        </div>
                        <div class="notification-container" data-vote-noti="2">
                            <div class="question-notification">
                                <a class="anchor-notification" href="#">How do you create classes in python ?</a> 
                            </div>
                            <div class="notification">votes 1 hour ago</div>
                        </div>
                        <div class="notification-container" data-vote-noti="3">
                            <div class="question-notification">
                                <a class="anchor-notification" href="#">How do you create classes in python ?</a> 
                            </div>
                            <div class="notification">votes 1 hour ago</div>
                        </div>
                    </div>
                </div>
                <div id="profile-link">
                    <img src="{{ url_for('static', filename='img/man.jpg') }}" alt="profile-photo">
                    <a href="{{ url_for('signin.profile') }}" ><h4 id="user-fullname">Andrew Njaya</h4></a>
                    <div id="logout-button">
                        logout
                    </div>
                </div>
            </div>
        </div>

        <!-- Left side bar -->
        <div id="my-profile-links">

        </div>
        <!-- Right side bar -->
        <div id="questions-topics">

        </div>
        <!-- Quentions body -->
        <div id="questions">
            <!--posting a question header -->
            <div class="post-question-heading">
                <h3>Post a question</h3>
            </div>
            <!-- errors -->
            <div id="question-errors">
                <li></li>
            </div>
            <!-- question form -->
            <div id="post-question">
                <div id="question-added-flash-message">
                    
                </div>
                <form enctype="multipart/form-data" method="post" id="post-question-form">
                    <!-- Question title -->
                    <div id="question-title-input">
                        <input type="text" name="title" id="" placeholder="Post a question...">
                    </div>
                    <!-- Description -->
                    <div id="question-description-textarea">
                        <textarea name="description" placeholder="Question description..." id="question-description" cols="0" rows="8"></textarea>
                    </div>
                    <!-- Question tags -->
                    <div id="question-tags">
                        <!-- <div class="tag">
                            <span class="label">JavaScript</span>
                            <span class="close-tag">&#9747;</span>
                        </div> -->
                        <!-- <div class="tag">
                            <span class="label">Css</span>
                            <span class="close-tag">&#9747;</span >
                        </div> -->
                        <input type="text" name="tags" id="tags-input" placeholder="Add a tag...">
                    </div>
                    <!-- Display question image to be upload -->
                    <div id="questionimage-to-upload">
                        <img id="display-image" src="" alt="question image to upload">
                        <!-- to remove the image -->
                        <span id="remove-question-image">Remove image</span>
                    </div>
                    <!-- Submit question button -->
                    <div id="submit-question-button">
                        <div>
                            <input type="file" name="image" id="question-image">
                            <label for="question-image">
                                <div class="upload-image">
                                    <img src="{{ url_for('static', filename='img/upload.png') }}" alt="upload image" srcset="">
                                </div>  
                                Choose...
                            </label>
                        </div>
                        <input type="submit" name="submit-question" value="Post" id="submit-question">
                    </div>
                </form>
            </div>
            <!--questions header -->
            <div class="post-question-heading">
                <h3>Posted questions</h3>
            </div>
            <!-- ============================ Posted questions ======================-->
            <div id="posted-questions">
                <!-- =============== First posted question ======================= -->

                <!--=== End of first posted question=== -->
                <!-- =======================Second posted question================= -->
  
                <!-- ====End of second posted question==== -->    
            </div>
            <!-- End of posted questions -->
                <!-- Login spin -->
            <div id="loader">
                <div class="loading">

                </div>
            </div>
        </div>
        <!-- End of questions body -->
        <!-- footer -->
        <div id="footer">
            &#9400; Find-Help 2020
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/questions.js' ) }}"></script>
</body>
</html>

templates/resetpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/resetpassword.css') }}">
    <title>Reset password</title>
</head>
<body>
    <!-- Body container -->
    <div id="body-container">
        <!-- navigation -->
        <div id="nav">
            <a href="{{ url_for('index') }}" id="left-item">FindHelp</a>
            <div id="right-item">
                <a href="{{ url_for('signin.login') }}" id="signin">Signin</a>
                <a href="{{ url_for('signin.signup') }}" id="signup">Signup</a>
            </div>
        </div>
        <!-- reset password body -->
        <div id="reset-body">
            <!-- reset container -->
            <div id="reset-container">
                <h2>Enter your email to reset your password</h2>
                <div id="reset-errors">
                    <li></li>
                </div>
                <!-- reset password form -->
                <form method="post" id="reset-form">
                    <input type="text" name="email" id="email" placeholder="Provide your email">
                    <input type="submit" value="Submit" id="submit">
                </form>
                <!-- signin and signup links -->
                <div id="signin-signup-links">
                    <a href="{{ url_for('signin.login') }}" id="login">Login</a>
                    <a href="{{ url_for('signin.signup') }}" id="register">Register</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/resetpassword.js' ) }}"></script>
</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FindHelp-Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css' ) }}">
</head>
<body>
    <!-- Container to hold all login details -->
    <div class="login-container">
        <!-- Login navigation bar -->
        <div id="login-navbar">
            <a id="login-homelink" href="{{ url_for('index') }}">FindHelp</a>
            <a id="login-signuplink" href="{{ url_for('signin.signup') }}">SignUp</a>
        </div>
        <!-- Login form -->
        <div id="login-body">
            <div id="inner-login-container">
                <!-- Login title -->
                <h1>Login</h1>
                <!-- errors -->
                <div id="login-errors">
                    <li></li>
                </div>
                <!-- Form -->
                <form method="post" enctype="multipart/form-data" id="login-form">
                    <!-- Email -->
                    <div id="email-label-div">
                        <label for="email" id="email-label">Email:</label>
                    </div>
                    <div id="email-textbox-div">
                        <input type="text" name="email" id="email">
                    </div>
                    <!-- Password -->
                    <div id="password-label-div">
                        <label for="password" id="password-label">Password:</label>
                    </div>
                    <div id="password-textbox-div">
                        <input type="password" name="password" id="password">
                    </div>
                    <!-- Submit button -->
                    <div id="submitdiv">
                        <input type="submit" value="Login" id="submit">
                    </div>
                    <!-- Reset password and signup links-->
                    <div id="reset-password-div">
                        <a href="{{ url_for('signin.request_reset') }}" id="resetpassword">Forgot password ?</a>
                    </div>
                    <div id="signup-div">
                        <a href="{{ url_for('signin.signup') }}" id="signedup">Already a member ?</a>
                    </div>
                </form>
                <!-- Login spin -->
                <div id="login-loader">
                    <div class="login-loading">

                    </div>
                </div>
            </div>
        </div>
        <!-- Login page footer -->
        <div id="login-footer">
             <li>&#9400; Find-Help 2020</li>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/signin.js' ) }}"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FindHelp SignUp</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signup.css') }}">
</head>
<body>
    <!-- Container to hold all sign up details -->
    <div class="signup-container">
        <!-- Signup navigation bar -->
        <div id="signup-navbar">
            <a id="signup-homelink" href="{{ url_for('index') }}">FindHelp</a>
            <a id="signup-signinlink" href="{{ url_for('signin.login') }}">Login</a>
        </div>
        <!-- Signup form -->
        <div id="signup-body">
            <div id="inner-signup-container">
                <!-- Signup title -->
                <h1>Sign Up</h1>
                <!-- signup errors -->
                <div id="signup-errors">
                    <li></li>
                </div>
                <!-- Form -->
                <form action="../auth/signin.html" method="post" id="signup-form">
                    <!-- Fullname -->
                    <div id="fullname-label-div" class="div-label">
                        <label for="fullname" id="email-label">Fullname:</label>
                    </div>
                    <div id="fullname-textbox-div">
                        <input type="text" name="username" id="fullname">
                    </div>
                    <!-- Email -->
                    <div id="email-label-div" class="div-label">
                        <label for="email" id="email-label">Email:</label>
                    </div>
                    <div id="email-textbox-div">
                        <input type="text" name="email" id="email">
                    </div>
                    <!-- Role -->
                    <div id="role-label-div" class="div-label">
                        <label for="role" id="role-label">Role:</label>
                    </div>
                    <div id="role-textbox-div">
                        <select name="role" id="role">
                            <option value=""></option>
                            <option value="true">User</option>
                            <option value="false">Moderate user</option>
                        </select>
                    </div>
                    <!-- Password -->
                    <div id="password-label-div" class="div-label">
                        <label for="password" id="password-label">Password:</label>
                    </div>
                    <div id="password-textbox-div">
                        <input type="password" name="password" id="password">
                    </div>
                    <!-- Confirm password -->
                    <div id="confirm-password-label-div" class="div-label">
                        <label for="confirmpassword" id="confirm-password-label">Confirm:</label>
                    </div>
                    <div id="confirm-password-textbox-div">
                        <input type="password" name="confirmpassword" id="confirmpassword">
                    </div>
                    <!-- Submit button -->
                    <div id="submit-div">
                        <input type="submit" value="Sign Up" id="submit">
                    </div>
                </form>
                <!-- Signup spin -->
                <div id="loader">
                    <div class="loading">

                    </div>
                </div>
            </div>
        </div>
        <!-- Login page footer -->
        <div id="signup-footer">
             <li>&#9400; Find-Help 2020</li>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/signup.js' ) }}"></script>  
</body>
</html>

templates/verifyemail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Email was successfully verified</h1>
    
</body>
</html>